from domain.repositories.role import RoleRepositoryAbstract
from domain.repositories.prefix_name import PrefixNameRepositoryAbstract
from domain.repositories.user import UserRepositoryAbstract
from domain.repositories.doctor import DoctorRepositoryAbstract
from domain.repositories.patient import PatientRepositoryAbstract
from domain.repositories.estimate_log import LogRepositoryAbstract
from domain.repositories.patient_list import PatientListRepositoryAbstract